---
title: "git_00"
author: "Eden Williams"
date: "Summer 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
’Twas brillig, and the slithy toves  
      Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
      And the mome raths outgrabe.  

## Second Verse
“Beware the Jabberwock, my son!  
      The jaws that bite, the claws that catch!  
Beware the Jubjub bird, and shun  
      The frumious Bandersnatch!” 
      
## Third Verse
He took his vorpal sword in hand;  
      Long time the manxome foe he sought—  
So rested he by the Tumtum tree  
      And stood awhile in thought.  
      
## Last Verse
Life will break you.  
Nobody can protect you from that, and living alone won't either, for solitude will also break you with its yearning.   
You have to love.   
You have to feel.   
It is the reason you are here on earth.   
You are here to risk your heart.   
You are here to be swallowed up.   
And when it happens that you are broken, or betrayed, or left, or hurt, or death brushes near, let yourself sit by an apple tree and listen to the apples falling all around you in heaps, wasting their sweetness.  
Tell yourself you tasted as many as you could.     
